config.durability = {
    ['weapon_pistol'] = { time = 12, usages = -1 },
    ['weapon_pistol_mk2'] = { time = 12, usages = -1 },
    ['weapon_snspistol'] = { time = 12, usages = -1 },
    ['weapon_snspistol_mk2'] = { time = 12, usages = -1 },
    ['weapon_revolver_mk2'] = { time = 12, usages = -1 },
    ['weapon_revolver'] = { time = 12, usages = -1 },
    ['weapon_microsmg'] = { time = 12, usages = -1 },
    ['weapon_minismg'] = { time = 12, usages = -1 },
    ['weapon_machinepistol'] = { time = 12, usages = -1 },
    ['weapon_heavyrifle'] = { time = 12, usages = -1 },
    ['weapon_compactrifle'] = { time = 12, usages = -1 },
    ['weapon_bullpuprifle_mk2'] = { time = 12, usages = -1 },
    ['weapon_specialcarbine_mk2'] = { time = 12, usages = -1 },
    ['weapon_tecpistol'] = { time = 12, usages = -1 },
    ['weapon_smg_mk2'] = { time = 12, usages = -1 },
    ['weapon_assaultsmg'] = { time = 12, usages = -1 },
    ['weapon_sawnoffshotgun'] = { time = 12, usages = -1 },
    ['weapon_pumpshotgun'] = { time = 12, usages = -1 },
    ['weapon_dbshotgun'] = { time = 12, usages = -1 },          
    ['weapon_gusenberg'] = { time = 12, usages = -1 },
    ['weapon_assaultrifle'] = { time = 12, usages = -1 },
    ['weapon_assaultrifle_mk2'] = { time = 12, usages = -1 },
    ['weapon_pistol50'] = { time = 12, usages = -1 },

    ['weapon_specialcarbine'] = { time = 12, usages = -1 },
    ['weapon_tacticalrifle'] = { time = 12, usages = -1 },
    ['weapon_wrench'] = { time = 12, usages = -1 },
    ['weapon_sniperrifle'] = { time = 12, usages = -1 },
    ['weapon_nightstick'] = { time = 12, usages = -1 },
    ['weapon_militaryrifle'] = { time = 12, usages = -1 },
    ['weapon_machete'] = { time = 12, usages = -1 },
    ['weapon_hammer'] = { time = 12, usages = -1 },
    ['weapon_crowbar'] = { time = 12, usages = -1 },
    ['weapon_combatshotgun'] = { time = 12, usages = -1 },
    ['weapon_combatpistol'] = { time = 12, usages = -1 },
    ['weapon_combatpdw'] = { time = 12, usages = -1 },
    ['weapon_ceramicpistol'] = { time = 12, usages = -1 },
    ['weapon_carbinerifle_mk2'] = { time = 12, usages = -1 },
    ['weapon_poolcue'] = { time = 12, usages = -1 },
    ['weapon_knuckle'] = { time = 12, usages = -1 },
    ['weapon_switchblade'] = { time = 12, usages = -1 },
    ['weapon_bat'] = { time = 12, usages = -1 },
    ['weapon_katana'] = { time = 12, usages = -1 },
    ['weapon_wrench'] = { time = 12, usages = -1 },    
    ['weapon_pao'] = { time = 12, usages = -1 },    
    ['weapon_picareta'] = { time = 12, usages = -1 },    
    ['weapon_placa'] = { time = 12, usages = -1 },    
    ['weapon_pumpshotgun_mk2'] = { time = 12, usages = -1 },
    ['weapon_petrolcan'] = { time = 12, usages = -1 },
    ['weapon_battleaxe'] = { time = 7, usages = -1 },
    ['weapon_musket'] = { time = 7, usages = -1 },
    ['weapon_bow'] = { time = 7, usages = -1 },
   
    ['algema'] = { time = 7, usages = -1 },
    ['chave-algema'] = { time = 7, usages = -1 },
    ['sabonete'] = { time = -1, usages = 1 },
    ['teste-quimico'] = { time = -1, usages = 3 },
    ['teste-residual'] = { time = -1, usages = 3 },
    ['chave-prisao'] = { time = 1, usages = 1 },

    ['cordas'] = { time = 7, usages = -1 },
    ['celular'] = { time = 7, usages = -1 },
    ['telefone'] = { time = -1, usages = 1 },
    ['vaper'] = { time = 10, usages = -1 },
    ['cigarro'] = { time = 3, usages = -1 },    
    ['radio'] = { time = 5, usages = -1 },   
    ['lockpick'] = { time = -1, usages = 3 },
    ['masterpick'] = { time = -1, usages = 3 },
    ['isqueiro'] = { time = 3, usages = -1 },
    ['capuz'] = { time = -1, usages = 4 },
    ['colete-militar'] = { time = 7, usages = -1 },
    ['colete-ilegal'] = { time = 7, usages = -1 },
    ['placa'] = { time = 7, usages = -1 },
    ['b-rastreador'] = { time = 7, usages = -1 },
    ['pager'] = { time = 7, usages = -1 },
    ['binoculos'] = { time = 7, usages = -1 },
    
    -- ['adrenalina'] = { time = 7, usages = -1 },
    ['camisaforca'] = { time = 7, usages = -1 },
    ['chave-camisaforca'] = { time = 7, usages = -1 },
    ['chave-ouro'] = { time = 7, usages = -1 },
    ['chave-platina'] = { time = 7, usages = -1 },
    ['tesoura'] = { time = 7, usages = -1 },
    ['equipamento-mergulho'] = { time = 7, usages = 1000 },
    
    ['flipper-mk1'] = { time = 7, usages = -1 },
    ['flipper-mk2'] = { time = 7, usages = -1 },
    ['flipper-mk3'] = { time = 7, usages = -1 },
    ['flipper-mk4'] = { time = 7, usages = -1 },
    ['flipper-mk5'] = { time = 7, usages = -1 },
    
    ['mascara'] = { time = 7, usages = -1 },
    ['sapatos'] = { time = 7, usages = -1 },
    ['chapeu'] = { time = 7, usages = -1 },
    ['oculos'] = { time = 7, usages = -1 },
    
    ['vara-pesca'] = { time = 7, usages = -1 },
    ['balde-leite'] = { time = 3, usages = -1 },
    
    ['nitro-roubado'] = { time = -1, usages = 1 },
    ['kit-desmanche'] = { time = 7, usages = -1 },
    ['kit-desmanche-novo'] = { time = 7, usages = -1 },
    ['tabletcorrida'] = { time = 5, usages = -1 },

    ['cp-radio'] = { time = 10, usages = -1 },   
    ['cp-powerbank'] = { time = -1, usages = 3 },   
    ['cp-lockpick'] = { time = -1, usages = 10 },   
    ['cp-cordas'] = { time = 14, usages = -1 },   
    ['cp-cigarro'] = { time = -1, usages = 3 },   
}