config.creator = {
    clothes = {
        [GetHashKey('mp_m_freemode_01')] = {
            [1] = { model = 0, var = 0, palette = 0 },
            [3] = { model = 15, var = 0, palette = 0 },
            [4] = { model = 21, var = 0, palette = 0 },
            [5] = { model = 0, var = 0, palette = 0 },
            [6] = { model = 34, var = 0, palette = 0 },
            [7] = { model = 0, var = 0, palette = 0 },
            [8] = { model = 15, var = 0, palette = 0 },
            [9] = { model = 0, var = 0, palette = 0 },
            [10] = { model = 0, var = 0, palette = 0 },
            [11] = { model = 15, var = 0, palette = 0 },
            [12] = { model = 0, var = 0, palette = 0 },
            ['p7'] = { model = -1, var = -1, palette = 0 },
            ['p6'] = { model = -1, var = -1, palette = 0 },
            ['p2'] = { model = -1, var = -1, palette = 0 },
            ['p0'] = { model = -1, var = -1, palette = 0 },
            ['p1'] = { model = -1, var = -1, palette = 0 },
            [0] = { model = 0, var = 0, palette = 0 },
        },
        [GetHashKey('mp_f_freemode_01')] = {
            [1] = { model = -1, var = 0, palette = 0 },
            [3] = { model = 15, var = 0, palette = 0 },
            [4] = { model = 15, var = 0, palette = 0 },
            [5] = { model = 0, var = 0, palette = 0 },
            [6] = { model = 35, var = 0, palette = 0 },
            [7] = { model = 0, var = 0, palette = 0 },
            [8] = { model = 15, var = 0, palette = 0 },
            [9] = { model = 0, var = 0, palette = 0 },
            [10] = { model = 0, var = 0, palette = 0 },
            [11] = { model = 15, var = 0, palette = 0 },
            [12] = { model = 0, var = 0, palette = 0 },
            ['p7'] = { model = -1, var = -1, palette = 0 },
            ['p6'] = { model = -1, var = -1, palette = 0 },
            ['p2'] = { model = -1, var = -1, palette = 0 },
            ['p0'] = { model = -1, var = -1, palette = 0 },
            ['p1'] = { model = -1, var = -1, palette = 0 },
            [0] = { model = 0, var = 0, palette = 0 },
        }
    },
    
    clothesFinish = {
        [GetHashKey('mp_m_freemode_01')] = {
            [1] = { model = 0, var = 0, palette = 0 },
            [3] = { model = 14, var = 0, palette = 0 },
            [4] = { model = 43, var = 0, palette = 0 },
            [5] = { model = 0, var = 0, palette = 0 },
            [6] = { model = 7, var = 6, palette = 0 },
            [7] = { model = 0, var = 0, palette = 0 },
            [8] = { model = 15, var = 0, palette = 0 },
            [9] = { model = 0, var = 0, palette = 0 },
            [10] = { model = 0, var = 0, palette = 0 },
            [11] = { model = 134, var = 0, palette = 0 },
            [12] = { model = 0, var = 0, palette = 0 },
            [0] = { model = 0, var = 0, palette = 0 },
            ['p6'] = { model = -1, var = -1, palette = 0 },
            ['p1'] = { model = -1, var = -1, palette = 0 },
            ['p0'] = { model = -1, var = -1, palette = 0 },
            ['p2'] = { model = -1, var = -1, palette = 0 },
            ['p7'] = { model = -1, var = -1, palette = 0 },
        },
        [GetHashKey('mp_f_freemode_01')] = {
            [1] = { model = -1, var = 0, palette = 0 },
            [3] = { model = 5, var = 0, palette = 0 },
            [4] = { model = 0, var = 0, palette = 0 },
            [5] = { model = 0, var = 0, palette = 0 },
            [6] = { model = 3, var = 0, palette = 0 },
            [7] = { model = 0, var = 0, palette = 0 },
            [8] = { model = 15, var = 0, palette = 0 },
            [9] = { model = -1, var = 0, palette = 0 },
            [10] = { model = 0, var = 0, palette = 0 },
            [11] = { model = 79, var = 0, palette = 0 },
            [12] = { model = 0, var = 0, palette = 0 },
            [0] = { model = 0, var = 0, palette = 0 },
            ['p6'] = { model = -1, var = -1, palette = 0 },
            ['p1'] = { model = -1, var = -1, palette = 0 },
            ['p0'] = { model = -1, var = -1, palette = 0 },
            ['p2'] = { model = -1, var = -1, palette = 0 },
            ['p7'] = { model = -1, var = -1, palette = 0 },
        }
    },

    coords = {
        creation = vector4(-811.5165, 175.2923, 76.72888, 99.21259),
        finish = vector4(-1108.339, -2860.048, 13.96338, 331.6535)
    }
}

ConfigCreator = config.creator

Cache.Cam = ''

Cache.Identity = {
    firstname = '',
    lastname = '',
    age = '',
}

Cache.Character = {
    gender = 'male',
    fatherId = 0,
    motherId = 21,
    shapeMix = 0.5,
    colorFather = 0,
    colorMother = 0,
    skinMix = 0.5,
    eyesColor = 0,
    eyesOpening = 0,
    eyebrowsHeight = 0,
    eyebrowsWidth = 0,
    eyebrowsModel = -1,
    eyebrowsColor = 0,
    eyebrowsOpacity = 1.0,
    noseWidth = 0,
    noseHeight = 0,
    noseLength = 0,
    noseBridge = 0,
    noseTip = 0,
    noseShift = 0,
    cheekboneHeight = 0,
    cheekboneWidth = 0,
    cheeksWidth = 0,
    lips = 0,
    jawWidth = 0,
    jawHeight = 0,
    chinLength = 0,
    chinPosition = 0,
    chinWidth = 0,
    chinShape = 0,
    neckWidth = 0,
    hairModel = 0,
    firstHairColor = 0,
    secondHairColor = 0,
    beardModel = -1,
    beardColor = 0,
    beardOpacity = 1.0,
    chestModel = -1,
    chestColor = 0,
    chestOpacity = 1.0,
    blushModel = -1,
    blushColor = 0,
    blushOpacity = 1.0,
    lipstickModel = -1,
    lipstickColor = 0,
    lipstickOpacity = 1.0,
    blemishesModel = -1,
    blemishesOpacity = 1.0,
    ageingModel = -1,
    ageingOpacity = 1.0,
    complexionModel = -1,
    complexionOpacity = 1.0,
    sundamageModel = -1,
    sundamageOpacity = 1.0,
    frecklesModel = -1,
    frecklesOpacity = 1.0,
    makeupModel = -1,
    makeupOpacity = 1.0,
    makeupColor = 0,
    makeupColorType = 0,
    addBodyBlemishes = -1,
    bodyBlemishes = -1,
    bodyBlemishesOpacity = 1.0,
}
