vRP._prepare('gb_bank/getPix', 'select chave from pix where user_id = @user_id')
vRP._prepare('gb_bank/editPix', 'update pix set chave = @chave where user_id = @user_id')
vRP._prepare('gb_bank/checkPix', 'select chave from pix where chave = @chave')
vRP._prepare('gb_bank/addPix', 'insert pix (user_id, chave) values (@user_id, @chave)')
vRP._prepare('gb_bank/delPix', 'delete from pix where user_id = @user_id')
vRP._prepare('gb_bank/addMultas', 'insert fine (user_id, fine_reason, fine_value, fine_time, fine_description) values (@user_id, @reason, @value, @time, @description)')
vRP._prepare('gb_bank/getMultas', 'select * from fine where user_id = @user_id')
vRP._prepare('gb_bank/getMulta', 'select * from fine where id = @multa_id')
vRP._prepare('gb_bank/delMulta', 'delete from fine where user_id = @user_id and id = @multa_id')
vRP._prepare('gb_bank/delAllMultas', 'delete from fine where user_id = @user_id')
-- coins --
vRP._prepare('capital_bank/get_coins', 'select coins from user_moneys where user_id = @userId')
vRP._prepare('capital_bank/set_coins', 'UPDATE user_moneys SET coins = @value where user_id = @userId')
vRP._prepare('capital_bank/add_coins', 'UPDATE user_moneys SET coins = coins + @value WHERE user_id = @userId')
vRP._prepare('capital_bank/rem_coins', 'UPDATE user_moneys SET coins = coins - @value WHERE user_id = @userId')