import { RiPlayFill } from "react-icons/ri";
import { RxUpdate } from "react-icons/rx";
import { BsFillHouseGearFill } from "react-icons/bs";
import { FaHouseUser } from "react-icons/fa";

export default [
  {
    title: "Upgrades",
    icon: <RxUpdate />,
    type: "category",
    action: "updates",
    value: "update",
    category: "homes",
  },
  {
    title: "Minha residência",
    icon: <FaHouseUser />,
    type: "category",
    action: "myHomes",
    value: "house",
    category: "homes",
  },
  {
    title: "Interior",
    icon: <BsFillHouseGearFill />,
    type: "category",
    action: "interior",
    value: "interior",
    category: "update",
  },
  {
    title: "Decoração",
    icon: <BsFillHouseGearFill />,
    type: "category",
    action: "decoration",
    value: "decoration",
    category: "update",
  },
  {
    title: "Aumentar baú",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesBau",
    value: null,
    category: "update",
    closeLater: true,
  },
  {
    title: "Aumentar Geladeira",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesFridge",
    value: null,
    category: "update",
    closeLater: true,
  },
  {
    title: "Aumentar guarda roupa",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesWardrobe",
    value: null,
    category: "update",
    closeLater: true,
  },
  {
    title: "Adicionar garagem",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesGaragem",
    value: null,
    category: "update",
    closeLater: true,
  },
  {
    title: "Remover garagem",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesDelGarage",
    value: null,
    category: "update",
    closeLater: true,
  },
  {
    title: "Pagar IPTU",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesTax",
    category: "house",
    closeLater: true,
  },
  {
    title: "Lista de casas",
    icon: <RiPlayFill />,
    type: "action",
    action: "blips",
    category: "homes",
    side: "client",
  },
  {
    title: "Checar moradores",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesChecar",
    category: "house",
    closeLater: true,
  },
  {
    title: "Adicionar morador",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesAdd",
    category: "house",
    closeLater: true,
  },
  {
    title: "Remover morador",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesRem",
    category: "house",
    closeLater: true,
  },
  {
    title: "Trancar/Destrancar casa",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesTrancar",
    category: "house",
  },
  {
    title: "Transferir a residência",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesTrans",
    category: "house",
    closeLater: true,
  },
  {
    title: "Vender a residência",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesVender",
    category: "house",
    closeLater: true,
  },
  {
    title: "Minhas residências",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesOther",
    category: "house",
    closeLater: true,
  },
  {
    title: "Interiores disponíveis",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesInterior",
    category: "interior",
    value: null,
    closeLater: true,
  },
  {
    title: "Interior simples",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesInterior",
    value: "simple",
    category: "interior",
    closeLater: true,
  },
  {
    title: "Interior solteiro",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesInterior",
    value: "single",
    category: "interior",
    closeLater: true,
  },
  {
    title: "Interior motel",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesInterior",
    value: "motel",
    category: "interior",
    closeLater: true,
  },
  {
    title: "Interior Luxo Branca",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesInterior",
    value: "high_01",
    category: "interior",
    closeLater: true,
  },
  {
    title: "Interior Luxo Vinho",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesInterior",
    value: "high_02",
    category: "interior",
    closeLater: true,
  },
  {
    title: "Interior Moderno Neutro",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesInterior",
    value: "apartment_01",
    category: "interior",
    closeLater: true,
  },
  {
    title: "Interior Moderno Laranja",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesInterior",
    value: "apartment_02",
    category: "interior",
    closeLater: true,
  },
  {
    title: "Interior Duplex",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesInterior",
    value: "eclip_penthouse",
    category: "interior",
    closeLater: true,
  },
  {
    title: "Decorações disponíveis",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesDecoration",
    value: null,
    category: "decoration",
    closeLater: true,
  },
  {
    title: "Decoração executiva",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesDecoration",
    value: "executive",
    category: "decoration",
    closeLater: true,
  },
  {
    title: "Decoração colorida",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesDecoration",
    value: "rainbow",
    category: "decoration",
    closeLater: true,
  },
  {
    title: "Decoração ampla",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesDecoration",
    value: "big",
    category: "decoration",
    closeLater: true,
  },
  {
    title: "Decoração minimalista",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesDecoration",
    value: "minimalist",
    category: "decoration",
    closeLater: true,
  },
  {
    title: "Decoração romance",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesDecoration",
    value: "red",
    category: "decoration",
    closeLater: true,
  },
  {
    title: "Decoração lavanda",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesDecoration",
    value: "purple",
    category: "decoration",
    closeLater: true,
  },
  {
    title: "Decoração oceano",
    icon: <RiPlayFill />,
    type: "action",
    action: "homesDecoration",
    value: "ocean",
    category: "decoration",
    closeLater: true,
  },
];
