import { RiPlayFill } from "react-icons/ri";
import { GiClothes, GiPoliceOfficerHead } from "react-icons/gi";

export default [
  {
    title: "Retirar",
    icon: <GiClothes />,
    type: "category",
    action: "vestimenta",
    value: "vestimenta",
    category: "police",
  },
  {
    title: "Retirar máscara",
    icon: <RiPlayFill />,
    type: "action",
    action: "vestimenta",
    value: "rmascara",
    category: "vestimenta",
  },
  {
    title: "Retirar chápeu",
    icon: <RiPlayFill />,
    type: "action",
    action: "vestimenta",
    value: "rchapeu",
    category: "vestimenta",
  },
  {
    title: "Acessórios",
    icon: <GiPoliceOfficerHead />,
    type: "category",
    action: "acessorios",
    value: "acessorios",
    category: "police",
  },
  {
    title: "Colocar cone",
    icon: <RiPlayFill />,
    type: "action",
    action: "acessorios",
    value: "cone",
    category: "acessorios",
  },
  {
    title: "Deletar cone",
    icon: <RiPlayFill />,
    type: "action",
    action: "acessorios",
    value: "coned",
    category: "acessorios",
  },
  {
    title: "Colocar barreira",
    icon: <RiPlayFill />,
    type: "action",
    action: "acessorios",
    value: "barreira",
    category: "acessorios",
  },
  {
    title: "Deletar barreira",
    icon: <RiPlayFill />,
    type: "action",
    action: "acessorios",
    value: "barreirad",
    category: "acessorios",
  },
  {
    title: "Fechar perímetro",
    icon: <RiPlayFill />,
    type: "action",
    action: "fecharperimetro",
    category: "police",
    closeLater: true,
  },
  {
    title: "Detido",
    icon: <RiPlayFill />,
    type: "action",
    action: "detido",
    category: "police",
  },
  // {
  //   title: "Prender",
  //   icon: <RiPlayFill />,
  //   type: "action",
  //   action: "prender",
  //   category: "police",
  // },
  // {
  //   title: "Retirar prisão",
  //   icon: <RiPlayFill />,
  //   type: "action",
  //   action: "tirarprisao",
  //   category: "police",
  // },
  // {
  //   title: "Reanimar",
  //   icon: <RiPlayFill />,
  //   type: "action",
  //   action: "reanimarpolicia",
  //   category: "police",
  // },
];
